/*
 * UI.java
 *
 * Created on 30.09.2011, 21:07:20
 */

package de.gaalop.gappDebugger;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author christian
 */
public class UI extends javax.swing.JFrame {

    /** Creates new form UI */
    public UI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButNextInstruction = new javax.swing.JButton();
        jButRun = new javax.swing.JButton();
        jButSetVariableValue = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListVariables = new javax.swing.JList();
        jButSetAlgebra = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListSrc = new javax.swing.JList();
        jButRestart = new javax.swing.JButton();
        jTextFieldInfo = new javax.swing.JTextField();
        jButLoadSrc1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GAPP Debugger");
        setMinimumSize(new java.awt.Dimension(955, 648));
        getContentPane().setLayout(null);

        jButNextInstruction.setText("Next instruction");
        jButNextInstruction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButNextInstructionActionPerformed(evt);
            }
        });
        getContentPane().add(jButNextInstruction);
        jButNextInstruction.setBounds(730, 100, 200, 25);

        jButRun.setText("Run");
        jButRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButRunActionPerformed(evt);
            }
        });
        getContentPane().add(jButRun);
        jButRun.setBounds(730, 130, 200, 25);

        jButSetVariableValue.setText("Set Variable Value");
        jButSetVariableValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButSetVariableValueActionPerformed(evt);
            }
        });
        getContentPane().add(jButSetVariableValue);
        jButSetVariableValue.setBounds(730, 70, 200, 25);

        jScrollPane2.setViewportView(jListVariables);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(730, 190, 200, 380);

        jButSetAlgebra.setText("Set algebra");
        jButSetAlgebra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButSetAlgebraActionPerformed(evt);
            }
        });
        getContentPane().add(jButSetAlgebra);
        jButSetAlgebra.setBounds(730, 10, 200, 25);

        jListSrc.setFont(new java.awt.Font("Arial", 0, 12));
        jScrollPane1.setViewportView(jListSrc);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 710, 560);

        jButRestart.setText("Restart");
        jButRestart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButRestartActionPerformed(evt);
            }
        });
        getContentPane().add(jButRestart);
        jButRestart.setBounds(730, 160, 200, 25);

        jTextFieldInfo.setEditable(false);
        getContentPane().add(jTextFieldInfo);
        jTextFieldInfo.setBounds(10, 580, 920, 19);

        jButLoadSrc1.setText("Load source");
        jButLoadSrc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButLoadSrc1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButLoadSrc1);
        jButLoadSrc1.setBounds(730, 40, 200, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButNextInstructionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButNextInstructionActionPerformed
        controller.nextInstruction();
    }//GEN-LAST:event_jButNextInstructionActionPerformed

    private void jButRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButRunActionPerformed
        controller.run();
    }//GEN-LAST:event_jButRunActionPerformed

    private void jButSetVariableValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButSetVariableValueActionPerformed
        controller.setVariableValue();
    }//GEN-LAST:event_jButSetVariableValueActionPerformed

    private void jButSetAlgebraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButSetAlgebraActionPerformed
        String algebraBlades = JOptionPane.showInputDialog(null, "Please type in the algebra basis vectors, separated by \",\"!","1,e1,e2,e3,einf,e0");
        if (algebraBlades != null && !algebraBlades.isEmpty())
            controller.setAlgebraBlades(algebraBlades);
    }//GEN-LAST:event_jButSetAlgebraActionPerformed

    private void jButRestartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButRestartActionPerformed
        controller.restart();
    }//GEN-LAST:event_jButRestartActionPerformed

    private void jButLoadSrc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButLoadSrc1ActionPerformed
        JFileChooser jFC = new JFileChooser();
        if (jFC.showOpenDialog(null) == JFileChooser.APPROVE_OPTION)
            controller.loadSource(jFC.getSelectedFile());
    }//GEN-LAST:event_jButLoadSrc1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButLoadSrc1;
    public javax.swing.JButton jButNextInstruction;
    private javax.swing.JButton jButRestart;
    public javax.swing.JButton jButRun;
    public javax.swing.JButton jButSetAlgebra;
    public javax.swing.JButton jButSetVariableValue;
    public javax.swing.JList jListSrc;
    public javax.swing.JList jListVariables;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTextField jTextFieldInfo;
    // End of variables declaration//GEN-END:variables

    public Controller controller;

    

}
