/*
 * UI.java
 *
 * Created on 30.09.2011, 21:07:20
 */

package de.gaalop.gappDebugger;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Christian Steinmetz
 */
public class UI extends javax.swing.JFrame {

    /** Creates new form UI */
    public UI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButNextInstruction = new javax.swing.JButton();
        jButRun = new javax.swing.JButton();
        jButSetVariableValue = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListVariables = new javax.swing.JList();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListSrc = new javax.swing.JList();
        jButRestart = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GAPP Debugger");
        setMinimumSize(new java.awt.Dimension(940, 600));
        getContentPane().setLayout(null);

        jButNextInstruction.setText("Next instruction");
        jButNextInstruction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButNextInstructionActionPerformed(evt);
            }
        });
        getContentPane().add(jButNextInstruction);
        jButNextInstruction.setBounds(430, 40, 180, 23);

        jButRun.setText("Run");
        jButRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButRunActionPerformed(evt);
            }
        });
        getContentPane().add(jButRun);
        jButRun.setBounds(430, 70, 180, 23);

        jButSetVariableValue.setText("Set Variable Value");
        jButSetVariableValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButSetVariableValueActionPerformed(evt);
            }
        });
        getContentPane().add(jButSetVariableValue);
        jButSetVariableValue.setBounds(430, 10, 180, 23);

        jScrollPane2.setViewportView(jListVariables);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(430, 130, 180, 440);

        jListSrc.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jScrollPane1.setViewportView(jListSrc);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 410, 560);

        jButRestart.setText("Restart");
        jButRestart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButRestartActionPerformed(evt);
            }
        });
        getContentPane().add(jButRestart);
        jButRestart.setBounds(430, 100, 180, 23);

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Blade", "Value"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(40);
        jTable1.getColumnModel().getColumn(0).setMaxWidth(40);
        jTable1.getColumnModel().getColumn(1).setMinWidth(0);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(90);
        jTable1.getColumnModel().getColumn(2).setMinWidth(0);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(90);
        jTable1.getColumnModel().getColumn(2).setMaxWidth(90);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(620, 10, 310, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButNextInstructionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButNextInstructionActionPerformed
        controller.nextInstruction();
    }//GEN-LAST:event_jButNextInstructionActionPerformed

    private void jButRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButRunActionPerformed
        controller.run();
    }//GEN-LAST:event_jButRunActionPerformed

    private void jButSetVariableValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButSetVariableValueActionPerformed
        controller.setVariableValue();
    }//GEN-LAST:event_jButSetVariableValueActionPerformed

    private void jButRestartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButRestartActionPerformed
        controller.restart();
    }//GEN-LAST:event_jButRestartActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButNextInstruction;
    private javax.swing.JButton jButRestart;
    public javax.swing.JButton jButRun;
    public javax.swing.JButton jButSetVariableValue;
    public javax.swing.JList jListSrc;
    public javax.swing.JList jListVariables;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    public Controller controller;

    

}
