package de.gaalop.gui;

import de.gaalop.OutputFile;

import javax.swing.*;
import java.util.Set;
import java.awt.*;

/**
 * This form is used to display compilation results.
 */
public class ResultForm {
    private JTabbedPane tabbedPane;
    private JPanel contentPane;

    private Set<OutputFile> files;

    public ResultForm(Set<OutputFile> files) {
        $$$setupUI$$$();

        for (OutputFile file : files) {
            JScrollPane filePane = new JScrollPane();
            JTextPane textPane = new JTextPane();
            textPane.setText(file.getContent());
            filePane.setViewportView(textPane);
            tabbedPane.add(file.getName(), filePane);
        }
    }

    public JPanel getContentPane() {
        return contentPane;
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new BorderLayout(0, 0));
        tabbedPane = new JTabbedPane();
        contentPane.add(tabbedPane, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }
}
