/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package de.gaalop.visualizer.gui;

/**
 *
 * @author christian
 */
public class DrawSettings extends javax.swing.JFrame {

    /**
     * Creates new form DrawSettings
     */
    public DrawSettings() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Settings = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane_Inputs = new javax.swing.JScrollPane();
        jPanel_Inputs = new javax.swing.JPanel();
        jButton_Repaint = new javax.swing.JButton();
        jLabel_Info = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel_Visible = new javax.swing.JPanel();
        jButton_LoadPointCloud = new javax.swing.JButton();
        jButton_SavePointCloud = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gaalop Visualization Settings");
        setMinimumSize(new java.awt.Dimension(485, 541));
        getContentPane().setLayout(null);

        jPanel_Settings.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Settings", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        javax.swing.GroupLayout jPanel_SettingsLayout = new javax.swing.GroupLayout(jPanel_Settings);
        jPanel_Settings.setLayout(jPanel_SettingsLayout);
        jPanel_SettingsLayout.setHorizontalGroup(
            jPanel_SettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 208, Short.MAX_VALUE)
        );
        jPanel_SettingsLayout.setVerticalGroup(
            jPanel_SettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 167, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel_Settings);
        jPanel_Settings.setBounds(240, 10, 220, 190);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Inputs", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout jPanel_InputsLayout = new javax.swing.GroupLayout(jPanel_Inputs);
        jPanel_Inputs.setLayout(jPanel_InputsLayout);
        jPanel_InputsLayout.setHorizontalGroup(
            jPanel_InputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 207, Short.MAX_VALUE)
        );
        jPanel_InputsLayout.setVerticalGroup(
            jPanel_InputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 378, Short.MAX_VALUE)
        );

        jScrollPane_Inputs.setViewportView(jPanel_Inputs);

        jPanel2.add(jScrollPane_Inputs);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 11, 220, 420);

        jButton_Repaint.setText("Repaint");
        jButton_Repaint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RepaintActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Repaint);
        jButton_Repaint.setBounds(300, 400, 90, 30);

        jLabel_Info.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel_Info);
        jLabel_Info.setBounds(20, 440, 430, 20);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Visible Objects", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout jPanel_VisibleLayout = new javax.swing.GroupLayout(jPanel_Visible);
        jPanel_Visible.setLayout(jPanel_VisibleLayout);
        jPanel_VisibleLayout.setHorizontalGroup(
            jPanel_VisibleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 206, Short.MAX_VALUE)
        );
        jPanel_VisibleLayout.setVerticalGroup(
            jPanel_VisibleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 155, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel_Visible);

        jPanel3.add(jScrollPane1);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(240, 210, 220, 180);

        jButton_LoadPointCloud.setText("Load Pointcloud");
        getContentPane().add(jButton_LoadPointCloud);
        jButton_LoadPointCloud.setBounds(20, 470, 130, 23);

        jButton_SavePointCloud.setText("Save Pointcloud");
        getContentPane().add(jButton_SavePointCloud);
        jButton_SavePointCloud.setBounds(180, 470, 140, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_RepaintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RepaintActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_RepaintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DrawSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DrawSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DrawSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DrawSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new DrawSettings().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton_LoadPointCloud;
    protected javax.swing.JButton jButton_Repaint;
    public javax.swing.JButton jButton_SavePointCloud;
    public javax.swing.JLabel jLabel_Info;
    protected javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JPanel jPanel_Inputs;
    protected javax.swing.JPanel jPanel_Settings;
    protected javax.swing.JPanel jPanel_Visible;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane_Inputs;
    // End of variables declaration//GEN-END:variables
    
}
