M7R0
I*conformalf*6#%"xG6"6$%)operatorG%&arrowGF&,(9$"""-%#&cG6$-F.6$F+F+%%einfG#F,"
"#%#e0GF,F&F&F&F&,
I%dualf*F$F&F'F&,$-F.6$F+%/e1we2we3we4we5G!""F&F&F&F&,
I&VecN3f*6%F%%"yG%"zGF&F'F&,,*&F+F,%#e1GF,F,*&9%F,%#e2GF,F,*&9&F,%#e3GF,F,*($""
&F<F,,(*$F+F4F,*$FFF4F,*$FIF4F,F,F2F,F,F5F,F&F&F&F&,
I(RotorE3f*6$F%%$angGF&F'F&,&-%$cosG6#,$FFF3F,*(-%$sinGFYF,F+F,-%(mul_absG6#F+F
<F<F&F&F&F&,
I(RotorN3f*6&F%F@FAFUF&F'F&,&-FX6#,$9'F3F,*(-FgnF`oF,,(*&F+F,%&e2we3GF,F<*&FFF,
%&e1we3GF,F,*&FIF,%&e1we2GF,F<F,FN#F<F4F,F&F&F&F&,
I-TranslatorN3f*F$6#%"tGF&F&C$@%/9#""$>8$,&F,F,*(F<F,FLF,*&,(*&&9"6#F,F,FDF,F,*
&&F^q6#F4F,FGF,F,*&&F^q6#FepF,FJF,F,F,F2F,F,F,Y6$QenTranslatorN3~expects~3~argu
ments,~but~received~%1~argumentF&FdpOFgpF&6#F2F&F&,
I)SphereN3f*6&F%F@FA%"rG6#%'sphereGF&F&C$@'/Fdp""%>Fgp,&-F=6%F+FFFIF,-F.6$-F.6$
FboFboF2F\p/FdpF4>Fgp,&F+F,-F.6$-F.6$FFFFF2F\pY6$QinSphereN3~expects~2~or~4~arg
uments,~but~received~%1~argument(s)F&FdpOFgpF&FjqF&F&,
I*quad_normf*F$F&F'F&-%%subsG6$/%#IdGF,-_%)CliffordG%#LCG6$F+-_Fat%*reversionGF
jnF&F&F&F&,
I(mul_absf*F$F&F'F&-%'wurzelG6#-FhsFjnF&F&F&F&,
I(inversef*F$F&F&F&@%/F\u""!OFauO-%)simplifyG6#*&FdtF,F\uF<F&F&F&F&,
I(reversef*F$F&F'F&FdtF&F&F&F&,
I(pick1stf*F$F&F'F&-%*pp_get1stGFjnF&F&F&F&,
I(pick2ndf*F$F&F'F&-%*pp_get2ndGFjnF&F&F&F&,
I*pp_get1stf*F$F&F'F&-Feu6#-F.6$-F[t6$F]t,&F+F<-%%sqrtG6#-%$absG6#F0F,-F]u6#-%-
innerproductG6$F+F2F&F&F&F&,
I*pp_get2ndf*F$F&F'F&-Feu6#-F.6$-F[t6$F]t,&F+F<F[wF<FawF&F&F&F&,
I'wurzelf*F$F&F'F&-F\w6#-F_w6#-_Fat%+scalarpartGFjnF&F&F&F&,
I-innerproductf*6$F%F@6#%'resultGF&F&C$>Fgp-F`t6$F+FF@%/FgpFauO-F`t6$FFF+OFgpF&
F&F&F&,
I#&if*F&F&F&F&O-Fdw6#F^qF&F&F&F&
